### ISSUE TITLE
Records sans resourceType

### ISSUE THREAD

**Issue by vbombaerts** [SPW-DIG/daobs#2]
En examinant mes TDB, je me rends compte que le nombre de records pour une date de harvesting n'est pas égal à la somme du nombre de dataset, series, application et services pour cette même date.

![2018-06-25 10_58_06-daobs](https://user-images.githubusercontent.com/6093597/41840708-b23c3c66-7866-11e8-837a-265a0f6d1810.png)

![2018-06-25 10_56_49-kibana](https://user-images.githubusercontent.com/6093597/41840663-977e4108-7866-11e8-9d6f-17b50980066a.png)

Dans l'explorateur de données, j'ai des records pour lesquels le resourceType = "-"
Une idée de ce que c'est ? C'est normal ?

PS : dans le screenshot, j'agrège sous l'appellation données les dataset et les series

**Comment by fxprunayre** [comment]
Ce serait top si on pouvait avoir un lien vers les recherches/visu/dashboards correspondant aux tickets pour tester.

**Comment by vbombaerts** [comment]
**[http://157.164.189.97/dashboard/dashboard/app/kibana#/dashboard/AWQoDL599n7va4nYzISa?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(description:'Indicateurs+relatifs+au+contenu+du+catalogue',filters:!(),options:(darkTheme:!f),panels:!((col:4,id:AWQjPe-v9n7va4nYzEWU,panelIndex:1,row:1,size_x:3,size_y:3,type:visualization),(col:7,id:AWQjG6Og9n7va4nYzEPF,panelIndex:4,row:1,size_x:6,size_y:3,type:visualization),(col:11,id:AWQjJc8K9n7va4nYzERP,panelIndex:5,row:4,size_x:2,size_y:3,type:visualization),(col:7,id:AWQjJACv9n7va4nYzEQ2,panelIndex:6,row:4,size_x:2,size_y:3,type:visualization),(col:9,id:AWQjJMlP9n7va4nYzERB,panelIndex:8,row:4,size_x:2,size_y:3,type:visualization),(col:1,id:AWQjLQiR9n7va4nYzESz,panelIndex:9,row:4,size_x:6,size_y:3,type:visualization),(col:1,id:AWQjMspr9n7va4nYzET_,panelIndex:10,row:1,size_x:3,size_y:3,type:visualization),(col:1,id:AWQjAOaT9n7va4nYzEJi,panelIndex:11,row:7,size_x:6,size_y:5,type:visualization)),query:(match_all:()),timeRestore:!f,title:'Test+-+Contenu+du+catalogue',uiState:(P-1:(vis:(legendOpen:!f)),P-4:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)'))),P-5:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)'))),P-6:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)'))),P-8:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)')))),viewMode:edit)](http://157.164.189.97/dashboard/dashboard/app/kibana#/dashboard/AWQoDL599n7va4nYzISa?_g=(refreshInterval:(display:Off,pause:!f,value:0),time:(from:now-5y,mode:quick,to:now))&_a=(description:'Indicateurs+relatifs+au+contenu+du+catalogue',filters:!(),options:(darkTheme:!f),panels:!((col:4,id:AWQjPe-v9n7va4nYzEWU,panelIndex:1,row:1,size_x:3,size_y:3,type:visualization),(col:7,id:AWQjG6Og9n7va4nYzEPF,panelIndex:4,row:1,size_x:6,size_y:3,type:visualization),(col:11,id:AWQjJc8K9n7va4nYzERP,panelIndex:5,row:4,size_x:2,size_y:3,type:visualization),(col:7,id:AWQjJACv9n7va4nYzEQ2,panelIndex:6,row:4,size_x:2,size_y:3,type:visualization),(col:9,id:AWQjJMlP9n7va4nYzERB,panelIndex:8,row:4,size_x:2,size_y:3,type:visualization),(col:1,id:AWQjLQiR9n7va4nYzESz,panelIndex:9,row:4,size_x:6,size_y:3,type:visualization),(col:1,id:AWQjMspr9n7va4nYzET_,panelIndex:10,row:1,size_x:3,size_y:3,type:visualization),(col:1,id:AWQjAOaT9n7va4nYzEJi,panelIndex:11,row:7,size_x:6,size_y:5,type:visualization)),query:(match_all:()),timeRestore:!f,title:'Test+-+Contenu+du+catalogue',uiState:(P-1:(vis:(legendOpen:!f)),P-4:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)'))),P-5:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)'))),P-6:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)'))),P-8:(vis:(defaultColors:('0+-+100':'rgb(0,104,55)')))),viewMode:edit))**

Voilà le lien, mais je ne sais pas si c'est ouvert hors infra SPW.
J'ai corrigé entretemps en en ajoutant le filtre "resourceType:exists"...

**Comment by fxprunayre** [comment]
Il ne faut pas oublier que l'index contient un mix de documents (et ce sera sans doute encore plus vrai par la suite - les features dans GN4 seront également dans l'index avec les fiches - car on ne peut pas faire de jointure inter-index dans ES)

Donc on a des documents qui actuellement correspondent à l'état d'avancement d'un harvester:
![image](https://user-images.githubusercontent.com/1701393/41842700-d6407898-786b-11e8-84ce-31448b7a952e.png)

Il faut donc les exclure et faire des recherches qui ne concernent que les fiches ie. ```+documentType:metadata``` pour avoir des visus que sur les fiches.

**Comment by vbombaerts** [comment]
OK. J'avais perdu ça de vue...
